nationalarchives/ds-caselaw-data-enrichment-service

- .github/workflows/terraform.yml
- modules/data/outputs.tf
- modules/data/secrets.tf
- modules/lambda_s3/lambda.tf
- modules/lambda_s3/variables.tf
- modules/network/local.tf
- modules/network/vpc.tf
- network/main.tf
- network/variables.tf
Signed-off-by: Adam King <adamking@Adams-MBP.lan>
> Formatted Terraform code

- .github/workflows/staging_build.yml
> added some echo statements

- .github/workflows/staging_build.yml
> should just need to do docker login once

- modules/lambda_s3/lambda.tf
- modules/lambda_s3/retention_policy.json
> keeping 12 docker images in each ECR

- modules/data/iam.tf
> Added IAM group

- modules/data/iam.tf
> setting a strong password policy as per AWS guidelines

- caselaw-ontology/README.markdown
- caselaw-ontology/examples/core-pipeline/README.markdown
- caselaw-ontology/examples/core-pipeline/ewhc_qb_2022_1678.ttl
- caselaw-ontology/ontology/caselaw.ttl
- caselaw-ontology/ontology/uk-court-system.ttl
Moving draft caselaw ontology files from vLex private repo into ds-caselaw-data-enrichment-service repo
> Move draft caselaw ontology into enrichment repo

- modules/data/locals.tf
- modules/data/rds.tf
> enabling deletion protection for prod

- abbreviation_extraction/abbreviations_matcher.py
- caselaw_extraction/caselaw_matcher.py
- lambda/push_enriched_xml/index.py
- lambda/update_legislation_table/index.py
- legislation_provisions_extraction/legislation_provisions.py
- modules/data/locals.tf
- replacer/replacer.py
> enabling deletion protection everywhere

- .github/workflows/apply.yml
- .github/workflows/production_build.yml
- .github/workflows/staging_build.yml
> moved the needs requirement

- .github/workflows/production_build.yml
> fixed which way round the prod keys are named

- modules/data/iam.tf
- modules/lambda_s3/bucket.tf
- modules/lambda_s3/data.tf
- modules/lambda_s3/lambda.tf
- modules/network/vpc.tf
> vcite enriched bucket, policy to be extended

- lambda/db_backup/dockerfile
- lambda/db_backup/index.py
- lambda/db_backup/requirements.txt
> Added code to perform db snapshot

- modules/lambda_s3/data.tf
- modules/lambda_s3/lambda.tf
> Added bucket policy for vcite_enriched

- modules/lambda_s3/bucket.tf
- modules/lambda_s3/eb.tf
- modules/lambda_s3/lambda.tf
> Added ECR, cron based eventbridge rule and bucket

- modules/lambda_s3/bucket.tf
- modules/lambda_s3/data.tf
> allowing vcite role to write to our bucket

- modules/lambda_s3/eb.tf
> using resources instead of module for eb

- .github/workflows/production_build.yml
- .github/workflows/staging_build.yml
> building the image for db-backup

- modules/lambda_s3/lambda.tf
> added the db backup lambda

- lambda/db_backup/dockerfile
- modules/lambda_s3/eb.tf
- modules/lambda_s3/lambda.tf
> removing lmb and ensuring image is in ecr first

- modules/lambda_s3/eb.tf
- modules/lambda_s3/lambda.tf
> enabled lambda

- lambda/db_backup/index.py
> fixed the timestamp in lambda code

- modules/lambda_s3/lambda.tf
> Adding RDS perms for backup lambda

- lambda/db_backup/index.py
- modules/lambda_s3/eb.tf
> moving to snapshot cluster not instance

- modules/lambda_s3/lambda.tf
> rds:Create*

- lambda/db_backup/index.py
> fixed the variable name for rds.get_waiter

- lambda/db_backup/index.py
> Changing the value that rds.waiter looks for

- lambda/db_backup/index.py
> Using s3.put_object to upload snapshot to S3

- lambda/db_backup/index.py
> amended s3.put_object syntax

- lambda/db_backup/index.py
> using s3.copy_object

- lambda/db_backup/index.py
- modules/lambda_s3/lambda.tf
> using start export task

- lambda/db_backup/index.py
> changed describe db cluster snapshots

- lambda/db_backup/index.py
> getting environment variable of bucket name

- modules/lambda_s3/lambda.tf
> Added assume role policy for lambda role

- lambda/db_backup/index.py
> using kms api

- lambda/db_backup/index.py
> using kms key id properly

- docs/README.md
> db backups docs

- lambda/db_backup/index.py
> describing a specific cluster snapshot

- lambda/db_backup/index.py
> removed confirmation check as it is always there at this stage

- abbreviation_extraction/abbreviations.py
- abbreviation_extraction/abbreviations_matcher.py
- caselaw_extraction/correction_strategies.py
- lambda/determine_legislation_provisions/index.py
- lambda/determine_oblique_references/index.py
- lambda/determine_replacements_abbreviations/index.py
- lambda/determine_replacements_caselaw/index.py
- lambda/determine_replacements_legislation/index.py
- lambda/extract_judgement_contents/index.py
- lambda/fetch_xml/index.py
- lambda/make_replacements/index.py
- lambda/push_enriched_xml/index.py
- lambda/update_legislation_table/index.py
- lambda/update_rules_processor/index.py
- lambda/vlex_upload/index.py
- lambda/xml_validate/index.py
- legislation_extraction/legislation_matcher_hybrid.py
- legislation_provisions_extraction/legislation_provisions.py
- replacer/replacer.py
- replacer/second_stage_replacer.py
- rules/correction_strategies.py
- utils/helper.py
Improvement of documentation in enrichment pipeline and lambdas
> Na 113 docs

- abbreviation_extraction/abbreviations.py
- abbreviation_extraction/abbreviations_matcher.py
- lambda/determine_legislation_provisions/index.py
- lambda/determine_oblique_references/index.py
- lambda/determine_replacements_abbreviations/index.py
- lambda/determine_replacements_caselaw/index.py
- lambda/determine_replacements_legislation/index.py
- lambda/extract_judgement_contents/index.py
- lambda/fetch_xml/index.py
- lambda/make_replacements/index.py
- lambda/push_enriched_xml/index.py
- lambda/update_legislation_table/index.py
- lambda/vlex_upload/index.py
- legislation_extraction/legislation_matcher_hybrid.py
- legislation_provisions_extraction/legislation_provisions.py
- modules/lambda_s3/bucket.tf
- modules/lambda_s3/lambda.tf
- modules/secure_bucket/data.tf
- modules/secure_bucket/kms.tf
- modules/secure_bucket/variables.tf
- replacer/replacer.py
- replacer/second_stage_replacer.py
- rules/correction_strategies.py
- tests/abbreviation_extraction_tests/test_abbreviations.py
- tests/lambda_tests/judgement_contents/test_extract_judgement_contents.py
- tests/lambda_tests/xml_validate/test_xml_validate.py
- tests/runner.py
> added a kms policy and only for vcite

- lambda/xml_validate/index.py
- modules/lambda_s3/data.tf
> fixed the role perms and formatted

- .github/workflows/ci_staging.yml
> installing specific version of black

- modules/secure_bucket/data.tf
- modules/secure_bucket/locals.tf
- modules/secure_bucket/variables.tf
> adding lambda roles to kms policy

- .pre-commit-config.yaml
Setting up a minimal set of pre-commits to match the linting rules that exist in the existing code
> Set up pre-commit hooks

- .gitignore
- lambda/determine_legislation_provisions/index.py
- oblique_references/oblique_references.py
- replacer/second_stage_replacer.py
- tests/legislation_provision_extraction_tests/test_legislation_provisions.py
- tests/replacer_tests/ewhc-ch-2023-257_enriched_stage_1.xml
- tests/replacer_tests/ewhc-ch-2023-257_enriched_stage_2.xml
- tests/replacer_tests/test_second_stage_replacer.py
Another prep pr for https://trello.com/c/Xvk7Zg67/455-enrichment-duplication-bug:
Changes in this PR:
- Add successful unit test case for provision_replacement
- Remove unused import of provision_replacement
- Added typehints and addressed mypy complaints in second_stage_replacer.py
> Bug/refactor replacer/455

- README.md
Fix links in README by referencing docs/ directory
> Fix links in README by referencing docs/ directory

- .pre-commit-config.yaml
- src/abbreviation_extraction/abbreviations.py
- src/lambdas/vlex_upload/index.py
- src/legislation_extraction/legislation_matcher_hybrid.py
- src/legislation_provisions_extraction/legislation_provisions.py
- src/tests/lambda_tests/xml_validate/test_xml_validate.py
- src/tests/oblique_reference_extraction_tests/test_oblique_references.py
- src/tests/test_pipeline_components/test_replacer.py
Add a precommit hook for mypy and silence errors. Some of these are significant issues which suggest the code would not have run (e.g. pass missing argument, no return value from a function leading to a codepath being impossible)
> Mypy precommit

- .github/workflows/ci_lint_and_test.yml
- .github/workflows/deploy_single_environment.yml
- .github/workflows/terraform_plan.yml
* we should delete the "On PRs, deploy to staging" action before merging.
* ~~there may be other parts of this where we `set -e` but they're for a different PR.~~
* we also get rid of a number of places we were using `set +e` where it wasn't raising an error.
* I'm not confident I'm doing the right thing with the jsonl file, but not sure what else would be right.
> Fix issues with github actions for deployment

- .github/workflows/deploy_single_environment.yml
- src/abbreviation_extraction/requirements.txt
- src/caselaw_extraction/requirements.txt
- src/lambdas/update_rules_processor/requirements.txt
- src/legislation_extraction/requirements.txt
- src/tests/requirements.txt
Changes:
- Fix xml_validate lambda by copying utils into xml_validate folder so it can import them
(also fix spacy issue)
> Copy utils into xml_validate folder so it can import them

- src/lambdas/fetch_xml/index.py
Does seem to do a lot more, these days.
> Remove comment about just listing S3 buckets

- terraform/modules/lambda_s3/queue.tf
Remove alerts being sent to Editha
> Task/remove editha alerts/997

- terraform/modules/lambda_s3/queue.tf
Fix function names being monitored for error alerts
> Fix function names being monitored for error alerts

- src/tests/test_xml_parser.py
- src/utils/helper.py
Intro tags were not being captured leading to their content not being enriched. Other tags might also be necessary but this fixes the immediate problem.
> Support other tags

- tools/see_prod.html
Type in URL (in either slash or hyphen form) and link directly to AWS page for XML or cloudwatch logs.
> See process of a judgment through the enrichment pipeline

- CHANGELOG.md
- src/lambdas/determine_legislation_provisions/index.py
- \[x\] Increase the version number in src/lambdas/determine_legislation_provisions/index.py
- \[x\] Update CHANGELOG.md
> bump to v6

- .github/workflows/deploy_single_environment.yml
- \[ \] Increase the version number in src/lambdas/determine_legislation_provisions/index.py
- \[ \] Update CHANGELOG.md
> Copy utils

- .github/workflows/ci_lint_and_test.yml
- .github/workflows/deploy_single_environment.yml
- Tiding up the CI workflow permissions and run conditions
- Adjust order of the workflow so it's easier to grok
- Remove unnecessary docker build step
> Tidy up CI build workflow

- terraform/modules/jump_host/iam.tf
* Policy is missing the 'Action'
> Fix Jump Host assume role policy

- terraform/modules/jump_host/ec2-instance.tf
* userdata needs to be base64 encoded
> Fix Jump Host ec2 userdata

- terraform/main.tf
- terraform/modules/data/rds.tf
- terraform/modules/data/variables.tf
- terraform/modules/jump_host/outputs.tf
* Allows accessing the RDS via the jump host
> Add Jump Host security group to RDS allowed security groups

- terraform/modules/data/aurora.tf
* Changed to use the correct parameter groups
> Fix RDS cluster parameter group

- terraform/modules/data/aurora.tf
* This should be fixed now with https://github.com/nationalarchives/ds-caselaw-data-enrichment-service/pull/454
> Uncomment aurora configuration

- terraform/modules/jump_host/ec2-userdata/jump-host.tpl
* Installs Docker on the jump host - Useful for using Postgres containers to connect to databases
* Also installs vim
> Add Docker to Jump Host

- terraform/main.tf
- terraform/modules/data/outputs.tf
* This changes the Lambda environment variables for the DB password (to reference the secret id of the new RDS) and the DB hostname
> Change Lambda RDS password and hostname

- pyproject.toml
- src/lambdas/determine_legislation_provisions/index.py
- src/lambdas/determine_oblique_references/index.py
- src/lambdas/determine_replacements_abbreviations/index.py
- src/lambdas/determine_replacements_caselaw/index.py
- src/lambdas/determine_replacements_legislation/index.py
- src/lambdas/extract_judgement_contents/index.py
- src/lambdas/make_replacements/index.py
- src/lambdas/update_rules_processor/index.py
- src/lambdas/vlex_upload/index.py
- src/lambdas/xml_validate/index.py
- src/legislation_provisions_extraction/legislation_provisions.py
- src/oblique_references/oblique_references.py
- src/replacer/second_stage_replacer.py
- src/tests/caselaw_extraction_tests/test_case_citations.py
- src/tests/replacer_tests/test_replacer_pipeline.py
- src/utils/compare_xml.py
- src/utils/environment_helpers.py
- validate_match_csv.py
Further refactors to the Enrichment codebase to bring it in line with our ruff standard rules.
FCL-218
> [FCL-218] Bring Enrichment into line with ruff linting standard

- .github/workflows/ci_lint_and_test.yml
Add a formatter check and a security check for the terraform code. This bring this repo more in line with the [dxw terraform template](https://github.com/dxw/terraform-template/)
> Add a couple of extra terraform actions

- src/abbreviation_extraction/requirements.txt
- src/caselaw_extraction/requirements.txt
- src/lambdas/update_rules_processor/requirements.txt
- src/legislation_extraction/requirements.txt
- src/tests/requirements.txt
Spacy and the language model need updating in sync.
> Use spacy 3.8.2

- .gitignore
- DESCRIPTION.md
- README.md
- scripts/get_schema
- scripts/validate_local
- tools/see_prod.html
Quality of life improvements:
* Validate local XML files via xmllint and downloading the schema locally
* Add replacement text files and css to log viewer
Nothing here impacts prod.
> Local validation tooling and improved log viewer

- CHANGELOG.md
- src/lambdas/determine_legislation_provisions/index.py
- src/lambdas/push_enriched_xml/index.py
- src/tests/lambda_tests/push_enriched_xml/test_push_enriched_xml.py
Fix encoding issue in push_enriched_xml lambda
> Fix encoding issue in push_enriched_xml lambda

- .github/workflows/ci_lint_and_test.yml
- .pre-commit-config.yaml
- pyproject.toml
- src/lambdas/update_legislation_table/update_legislation_table/database.py
- src/utils/proper_xml.py
Swap codeclimate for code cov and bandit
> Swap codeclimate for code cov and bandit
