nationalarchives/ds-caselaw-data-enrichment-service

- .gitignore
- abbreviation_extraction/abbreviations.py
- abbreviation_extraction/abbreviations_matcher.py
> fix abbreviations - not catching capitals at end

- legislation_extraction/legislation_matcher_hybrid.py
Fixed the bug where two acts would link up to overlapped text segments referencing the same legislation (byproduct of fuzzy matching). This was tested locally in standalone mode and would need to be tested as part of the pipeline before merging.
> Added a function to resolve overlapped references

- abbreviation_extraction/abbreviations.py
previous fix would have forced last character to be upper case, now it must be upper case OR a number to allow for dates in the short form
> allow for dates in short form

- lambda/db_backup/index.py
The Amazon Resource Name (ARN) for the DB cluster snapshot.
SourceDBClusterSnapshotArn (string) --
If the DB cluster snapshot was copied from a source DB cluster snapshot, the Amazon Resource Name (ARN) for the source DB cluster snapshot, otherwise, a null value.
> corrected source. DBClusterSnapshotArn (string) --

- lambda/push_enriched_xml/index.py
Editors discovered that the Enrichment pipeline was leaving things locked.
We observed the pipeline locking and checking the locks on documents (`fetch_xml`) but no PATCH requests
from trying to upload the document (in `push_enriched_xml`).
The AWS logs for the `push_enriched_xml` lambda (see page 2) said:
```
[ERROR] UnboundLocalError: local variable 'api_endpoint' referenced before assignment
Traceback (most recent call last):
...
File "/var/task/index.py", line 111, in process_event
api_endpoint == "https://api.caselaw.nationalarchives.gov.uk/"```
so we are fixing that one line so it's an assignment not a test of equality.
Not yet sure about testing etc.
> Fix typo in assigning api_endpoint that blocked enrichment pre-PATCH

- .github/workflows/archive/terraform.yml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Remove deprecated set-output

- .github/workflows/cd_deploy_staging_then_prod.yml
There was a bug in the deployment CICD workflow in PR: ta-enrichment-service/pull/165 which was only noticed when run on main.
This fixes it.
> Fix the tidied up deploy workflow after realising error once merged to main

- lambda/determine_oblique_references/index.py
- oblique_references/enrich_oblique_references.py
The bug https://trello.com/c/Xvk7Zg67/455-enrichment-duplication-bug is caused by the oblique_reference lambda. 
This first PR tidies that up first so that latter PRs are simpler
> Bug/clean up oblique ref lambda/455

- oblique_references/oblique_references.py
Second preparatory PR for fixing https://trello.com/c/Xvk7Zg67/455-enrichment-duplication-bug
This PR makes the following changes to `oblique_references/oblique_references.py` which is the main file that gets adjusted in the upcoming fix for the bug:
- Added typehints to all functions
- Fixed all issues mypy had with the file
- Fixed an edge case where we were returning empty list instead of empty dict
- Fixed long lines
I installed
```
mypy==1.1.1
types-beautifulsoup4==1.1.11.12
```
locally to get mypy to run on the file. I also had to delete the `__init__.py` file in the root directory for it to run as it didnt like the non-snakecase project name `ds-caselaw-data-enrichment-service`.
---------------------------------------------------------
---- Side mypy and dev dependency discussion …
> Bug/refactor oblique references/455

- .github/workflows/ci_lint_and_test.yml
https://trello.com/c/Z8QT4CCd/606-add-test-coverage-to-enrichment-repo
Added Codeclimate codecoverage integration.
Have set the coverage threshold to 75% on codeclimate dashboard for now as we are just over that in the first report we have here.
> Upload code coverage report to codeclimate on CI

- README.md
https://trello.com/c/tDM43BiC/615-add-documentation-for-debugging-enrichment-pipeline-bugs
I have worked on a couple of the first enrichment bugs since handover and have come up with a good debugging method for failed enrichment.
This PR adds documentation for others to debug enrichment more easily
> Add debugging section to README

- src/legislation_extraction/legislation_matcher_hybrid.py
- src/tests/legislation_extraction_tests/test_legislation_citations.py
It looks like there's an issue where we're deleting things from a loop, and if there's three entries, we might delete one that then isn't there later, causing a crash.
> Fix resolve overlap

- src/lambdas/update_legislation_table/index.py
- src/lambdas/update_rules_processor/index.py
We were previously catching all `Exception`s in `update_legislation_table` and `update_rules_processor`.
We noticed this when creating https://trello.com/c/RTIrUXGl/640-enrichment-legislation-table-not-been-updated-in-ages
since this `update_legislation_table` was erroring and showing so in the logs but the lambda function run was not failing as we did not reraise the exception after catching and logging like we do in all other lambda handler functions.
PR:
- Made sure to reraise caught exceptions in `update_legislation_table` and `update_rules_processor`
- Remove misleading postgres related info in exception
- Moved around some try except blocks in `update_rules_processor`
> Bug/dont catch lambda errors/640

- src/lambdas/update_legislation_table/index.py
**Background:**
For whatever reason, there was no code in the codebase setting the `year` column in the `ukpga_lookup` table which exists in production and is accessed in the lambda for enriching legislation in a document.
When it isn't there, those legislations are ignored.
From 2021 and earlier, apart from the final legislation of that year `Armed Forces Act 2021` had the year populated in the production db, however, everything from 2022 onwards was not.
I have manually fixed that on the production server.
**Purpose of this PR:**
- makes sure all newly synced legislations (the lambda runs weekly to sync the db up with the legislation in the legislation service from the past week) include year.
Note: the legislation before 2018 don't seem to have the year field in the legislation …
> Update legislation update lambda to set year of legislations in db

- src/database/db_connection.py
- src/lambdas/determine_legislation_provisions/index.py
- src/lambdas/determine_oblique_references/index.py
- src/lambdas/determine_replacements_abbreviations/index.py
- src/lambdas/determine_replacements_caselaw/index.py
- src/lambdas/determine_replacements_legislation/index.py
- src/lambdas/extract_judgement_contents/index.py
- src/lambdas/fetch_xml/index.py
- src/lambdas/update_legislation_table/index.py
- src/lambdas/update_rules_processor/index.py
- src/lambdas/xml_validate/index.py
- src/utils/environment_helpers.py
- src/utils/initialise_db.py
- src/utils/tests/conftest.py
- src/utils/tests/test_environment_helpers.py
- src/utils/tests/test_initialise_db.py
- terraform/modules/lambda_s3/lambda.tf
This PR:
- Reduces database env var reading boiler plate
- make database env var names more explicit (without prefixing DATABASE_ to PASSWORD to make DATABASE_PASSWORD, sourcing a .env locally would mess up the shell so this was necessary as I added that new env as discussed in comments)
- and remove unused TABLE_NAME env var (discussed in comments)
> Simplify db env vars

- .github/workflows/deploy_single_environment.yml
This PR does the final fixes to the terraform regarding the shared utils folder used in various lambdas.
The previous fix PR didnt do everything that was needed and had some typos/bugs in it itself: https://github.com/nationalarchives/ds-caselaw-data-enrichment-service/pull/202
> Properly fix file copying of shared utils files in terraform deployment

- src/lambdas/update_legislation_table/index.py
- src/lambdas/update_legislation_table/test_update_legislation.py
- src/lambdas/update_legislation_table/update_legislation_table/database.py
- src/lambdas/update_legislation_table/update_legislation_table/tests/test_remove_duplicates.py
https://trello.com/c/RTIrUXGl/640-enrichment-legislation-table-not-been-updated-in-ages
The enrichment service has a db which just mirrors the legislation api's db (for efficiency reasons.
Without this PR, the lambda used to keep it up to date `update_legislation_table` _could_ add duplicate entries to the db if the trigger_date went back to a date already covered by the db.
This PR addresses that and removes any duplicate entries at the end of the `update_legislation_table` lambda.
> remove_duplicates as part of update_legislation_table lambda

- .github/workflows/deploy_single_environment.yml
- src/lambdas/update_legislation_table/Dockerfile
- src/lambdas/update_rules_processor/Dockerfile
Let's hope this fixes update_legislation_table once and for all. locally I had copied the database folder into the update_leg folder so building the image worked.
Also double checked what other lambdas used the init_db functions added recently to the database shared folder and noticed we needed to fix `update_rules_processor` also.
We need to sort out the whole copying of shared folders - which we have a ticket for.
Also need to start running the unit tests in the same env that the lambdas run in so we dont have these issues once we merged in to main. But that will be a separate ticket. Probably a followup to the ticket on shared folders.
> Fix update_legislation_table and update_rules_processor FINALLY

- src/lambdas/update_legislation_table/requirements.txt
We had updated sqlalchemy to 2.0.0 but only newer versions of pandas df.to_sql is compatible with it, so upgrading pandas  to 1.5.3.
- again not caught by unit tests in ci due to how we have the test env/lambda env set up - ticket to address this exists.
more info on this here: https://stackoverflow.com/questions/75273632/got-multiple-values-for-argument-schema
> Upgrade pandas to 1.5.3

- terraform/modules/lambda_s3/lambda.tf
Reverts nationalarchives/ds-caselaw-data-enrichment-service#208 since it broke the determine casleaw lambda again which means that the underlying issue of deploying new lambdas  https://trello.com/c/lLABy4j9/791-certain-enrichment-lambda-functions-not-updating-on-merge-even-though-terraform-updating-env-variables-causing-errors isnt fixed yet.
> Revert "Remove env vars that were temporarily addedback in until deployment b…"

- terraform/modules/lambda_s3/queue.tf
Extends the alerts me and @dragon-dxw get to all lambda functions currently in the enrichment aws space.
Will have a followup PR where I simplify the queue file substantially so we dont have to define the sns topics etc for each function, and so that they are generated dynamically for all current functions - that way we will never be out of the loop if a function is renamed or is added! Also, it will allow us to specify a config of developers/ external services we want to subscribe to the enrichment errors!
> Task/alert us of enrichment errors/997

- terraform/modules/lambda_s3/queue.tf
- terraform/modules/lambda_s3/variables.tf
https://trello.com/c/NrZGHaJg/997-some-enrichment-lambda-functions-arent-alerting-us-of-errors
Breaking Changes:
- all the topics into one new topic called `Enrichment Error` as opposed to specific ones like `Fetch XML Error`, but the underlying errors alerts for each lambda function will still exist and are distinguishable within each topic.
Refactor-Only Changes:
- All lambda functions now have their corresponding error `aws_cloudwatch_metric_alarm` created  dynamically rather than lots of duplicated boilerplate - utilising the `count` meta-argument https://developer.hashicorp.com/terraform/language/meta-arguments/count
- Subscriptions to the new topic has less boilerplate by using a email list variable.
> Reduce duplication in queue tf file

- src/caselaw_extraction/requirements.txt
- src/lambdas/determine_legislation_provisions/Dockerfile
- src/legislation_extraction/requirements.txt
https://trello.com/c/1f3avRgA/1041-broken-lambda-functions
Fixes lambda issues with lambda dependencies that were missing that I noticed on staging when testing https://github.com/nationalarchives/ds-caselaw-data-enrichment-service/pull/224
Hasnt been a problem in production due to a deployment bug which means the lambdas that were affected werent actually up to date on. We have a ticket for that and will be dealt with separately
> Fix lambda utils folder dependency issues

- terraform/modules/lambda_s3/lambda.tf
There were OOM issues with the megajudgment.
https://trello.com/c/TDttis5D/1180-megajudgment-enrichment-determine-replacements-caselaw-oom-error
> Double determine-replacements-caselaw ram

- src/lambdas/make_replacements/index.py
- src/replacer/make_replacments.py
- src/replacer/replacer_pipeline.py
- src/tests/fixtures/ewhc-ch-2023-257_original.xml
- src/tests/fixtures/ewhc-ch-2023-257_replacements.txt
- src/tests/replacer_tests/test_make_replacements.py
**Bug details:**
Enrichment was failing to make replacements for for documents without header tags. Spcifically erroring with:
```
[ERROR] IndexError: list index out of range
Traceback (most recent call last):
File "/var/task/index.py", line 219, in handler
process_event(sqs_rec)
File "/var/task/index.py", line 135, in process_event
judgment_split[2], replacement_file_content
[ERROR] IndexError: list index out of range Traceback (most recent call last):   File "/var/task/index.py", line 219, in handler     process_event(sqs_rec)   File "/var/task/index.py", line 135, in process_event     judgment_split[2], replacement_file_content
```
**Changes in this PR:**
- This fixes this bug by fixing the splitting logic.
- Also refactored the main lambda function, extracting out the main logic away …
> Fcl 151 enrichment broken for documents without header tags

- .github/workflows/ci_lint_and_test.yml
- .pre-commit-config.yaml
- README.md
- caselaw-ontology/examples/core-pipeline/2019-ewhc-1-costs-rdf-example.ttl
- caselaw-ontology/examples/core-pipeline/tna-example.ttl
- src/utils/tests/test_environment_helpers.py
- terraform/README.md
This simplifies the test task by removing a bunch of independent tasks into a single "run pre-commit" job. This also improves parity between the checks run locally at commit-time and those running on CI.
> Run pre-commit in CI to check things, instead of firing them individually

- .github/workflows/ci_lint_and_test.yml
- .github/workflows/deploy_single_environment.yml
- setup.cfg
- src/abbreviation_extraction/requirements.txt
- src/caselaw_extraction/requirements.txt
- src/lambdas/determine_legislation_provisions/Dockerfile
- src/lambdas/determine_replacements_abbreviations/Dockerfile
- src/lambdas/determine_replacements_caselaw/Dockerfile
- src/lambdas/determine_replacements_legislation/Dockerfile
- src/lambdas/fetch_xml/dockerfile
- src/lambdas/push_enriched_xml/dockerfile
- src/lambdas/update_rules_processor/requirements.txt
- src/legislation_extraction/legislation_matcher_hybrid.py
- src/legislation_extraction/requirements.txt
- src/tests/requirements.txt
- terraform/modules/lambda_s3/lambda.tf
- terraform/modules/lambda_s3/variables.tf
We updated to Python 3.12 in some places, but not everywhere. This is a likely contributor to things not working.
Move all references to Python 3.12 and then fix the fallout.
> Actually use Python 3.12 everywhere

- renovate.json
Renovate skips some directories: see https://github.com/renovatebot/renovate/discussions/12755
No idea if this actually works.
> Renovate test requirements.txt

- renovate.json
We want an empty ignore list, so that dependencies in tests are properly updated.
> Fix Renovate ignore config

- .github/workflows/ci_lint_and_test.yml
We should use merge queues to streamline getting lots of PRs in for dependency updates without running the (very expensive) build process over and over.
> Run CI in merge queue

- .github/pull_request_template.md
- CHANGELOG.md
- README.md
- src/lambdas/determine_legislation_provisions/index.py
- src/replacer/replacer_pipeline.py
- src/tests/lambda_tests/determine_legislation_provisions/test_determine_legislation_provisions.py
- src/tests/replacer_tests/test_replacer_pipeline.py
`<ref>` tags were being emitted with `uk:year="No Year"`. Whilst it's not clear where the `No Year` is coming from (the database doesn't seem to have it, nor does the code) we detect non-year containing strings and do not provide a `uk:year` attribute at all.
We also set up groundwork for a versioning scheme.
> Move to integer based versioning and fix "no year" case for refs

- src/replacer/make_replacments.py
- src/tests/replacer_tests/test_make_replacements.py
* don't use regex to parse XMLs
* discovered `method="c14n2"` to produce canonical XML output to compare two trees.
> Remove only uk:origin=tna ref tags

- CHANGELOG.md
- src/lambdas/determine_legislation_provisions/index.py
- src/lambdas/fetch_xml/index.py
- terraform/modules/lambda_s3/queue.tf
The lambda does not check for `trigger_enrichment` as a message attribute, it checks the body for `publish`; we adjust the terraform to filter trigger_enrichment so we can not trigger the lambda at all and therefore delete that check from the lambda.
- \[x\] Update CHANGELOG.md
> Filter SQS on trigger_enrichment presence

- terraform/modules/lambda_s3/eb.tf
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_rule#argument-reference
```
Warning: Argument is deprecated
with module.lambda_s3.aws_cloudwatch_event_rule.db_backup,
on modules/lambda_s3/eb.tf line 4, in resource "aws_cloudwatch_event_rule" "db_backup":
4:   is_enabled          = true # update last
Use "state" instead
```
> Swap deprecated is_enabled argument for state

- .github/workflows/deploy_single_environment.yml
Previously, although the Docker images behind these Lambdas were being updated and re-tagged, the Lambda functions themselves were not being told about the code updates.
They are now instructed to redeploy once images are updated.
Fixes #107.
> Update image-based Lambda functions at deploy time

- CHANGELOG.md
- src/lambdas/determine_legislation_provisions/index.py
- src/legislation_provisions_extraction/legislation_provisions.py
- src/oblique_references/oblique_references.py
- src/replacer/replacer_pipeline.py
- src/tests/legislation_provision_extraction_tests/test_legislation_provisions.py
- src/tests/oblique_reference_extraction_tests/test_determine_and_replace_oblique_references.py
- src/tests/oblique_reference_extraction_tests/test_oblique_references.py
- src/tests/replacer_tests/test_replacer_pipeline.py
- src/utils/proper_xml.py
- src/utils/tests/test_proper_xml.py
Handle the XML replacements as actual XML (`create_tag` and `create_tag_string`), and escape some input strings that aren't from the XML.
Not sure if we should just do the string escaping separatly and maybe not do the create_tag work?
- \[x\] Increase the version number in src/lambdas/determine_legislation_provisions/index.py
- \[x\] Update CHANGELOG.md
> Better XML generation -- 

- src/replacer/second_stage_replacer.py
- src/tests/oblique_reference_extraction_tests/test_determine_and_replace_oblique_references.py
- src/tests/replacer_tests/test_make_replacements.py
- src/tests/replacer_tests/test_second_stage_replacer.py
- src/utils/compare_xml.py
- src/utils/tests/compare_xml.py
- src/utils/tests/test_proper_xml.py
When you initialise BeautifulSoup, you can provide a parser argument. This defaults to HTML, but the rest of Enrichment provides an argument of `"xml"`, which uses Python's default XML parser. In this case, however, the argument was "lxml", which sounds like it should use `lxml.etree`, but it doesn't. Instead it uses `lxml.html`, which converts all tags to lowercase. Unfortunately, XML's tags are case sensitive and this causes explosions with some of our case-sensitive tags such as `authorialNote`.
However, when we remove the `l`, we hit another problem. BeautifulSoup is a forgiving parser, sees that there are no namespaces defined and just throws them away. We wrap the tag in another tag with a defined `uk:` namespace, which BeautifulSoup then pulls just the paragraph from.
> Fix case where `replace_references_by_paragraph` was treating XML as HTML

- src/oblique_references/oblique_references.py
- src/tests/oblique_reference_extraction_tests/test_oblique_references.py
Permit `uk:canonical` or `canonical` as attributes of ref tags
> Be flexible about soup namespaces for canonical§

- src/database/requirements.txt
- src/lambdas/db_backup/requirements.txt
- src/lambdas/extract_judgement_contents/requirements.txt
- src/lambdas/fetch_xml/requirements.txt
- src/lambdas/make_replacements/requirements.txt
- src/lambdas/push_enriched_xml/requirements.txt
- src/lambdas/update_legislation_table/requirements.txt
- src/lambdas/update_rules_processor/requirements.txt
- src/lambdas/xml_validate/requirements.txt
- src/legislation_provisions_extraction/requirements.txt
- src/oblique_references/requirements.txt
- src/replacer/requirements.txt
- src/utils/requirements.txt
This reverts commit 5e30979763fb04132b0cbd9e262351fd1d9ea1dd.
We don't need it because we're only importing spacy for type checking.
- \[ \] Increase the version number in src/lambdas/determine_legislation_provisions/index.py
- \[ \] Update CHANGELOG.md
> Revert "Add spacy to all the requirements"

- src/abbreviation_extraction/abbreviations_matcher.py
- src/lambdas/determine_replacements_abbreviations/index.py
- src/lambdas/determine_replacements_legislation/index.py
We're getting `module 'spacy.lang' has no attribute 'en'` errors in determine-replacements-legislation. There's probably a reasonable way of doing this but let's not right now.
> Remove all NLP typing

- src/lambdas/fetch_xml/index.py
We set an `expires` value that isn't 0; that will make it any lock expire at midnight. It's set to 3600 to make it less painful if/when we change the behaviour to expiring in a number of seconds.
This will need updating in api client and priv api.
> Auto unlock if timeout

- src/replacer/make_replacments.py
- src/tests/replacer_tests/test_make_replacements.py
Whilst reparsing would fix this, it's good to be able to reenrich the old stuff without spurious failures which means the queue will never empty.
The uk:origin attribute does not exist for vCite-enriched judgments in the backlog.
> Remove ref tags that have no uk:origin attribute

- LICENSE.md
Ensure that the licence declares Crown Copyright and not just (c) The National Archives
> crown copyright in licence file

- terraform/README.md
- terraform/main.tf
- terraform/modules/github_oidc/data.tf
- terraform/modules/github_oidc/external-data-scripts/get-certificate-thumbprint.sh
- terraform/modules/github_oidc/locals.tf
- terraform/modules/github_oidc/main.tf
- terraform/modules/github_oidc/variables.tf
* Creates an OpenID Connect provider for GitHub, with permissions to only allow access from a specific repository.
* The certificate thumbprint has changed previously (when GitHub update their certificates), so a script has been added to get the latest thumbprint - which is then passed to the OpenID connect provider
* Currently the managed AdministratorAccess policy has been attached to the Role that the OpenID Connect provider is allowed to assume - Though we should determine minimum permissions and create our own policy.
> Terraform GitHub OpenID Connect

- terraform/main.tf
- terraform/modules/github_oidc/data.tf
- terraform/modules/github_oidc/locals.tf
- terraform/modules/github_oidc/main.tf
- terraform/modules/github_oidc/variables.tf
* Only 1 provider configured with the GitHub url is allowed
* This adds a variable `github_oidc_create_provider` to conditionally create the provider. Set to `false` if the provider already exists, and the trusted role will be created with the existing provider arn.
> Conditionally create GitHub OpenID Connect provider

- terraform/modules/jump_host/ec2-userdata/jump-host.tpl
* The AWS SSM Agent isn't pre installed on Amazon Linux 2023 (Even though URL includes an ec2-downloads-windows directory, this is the correct installation files for Amazon Linux 2023 - https://docs.aws.amazon.com/systems-manager/latest/userguide/agent-install-al2.html)
> Install SSM Agent on Jump Host

- terraform/modules/jump_host/iam.tf
* The resorce for the ssm settings should be the ARN of the dhmc setting
> Fix Jump Host SSM DHMC policy

- terraform/modules/jump_host/network.tf
* The jump host will most likely need external access to multiple services
> Allow all egress from jump host

- terraform/modules/jump_host/ec2-instance.tf
* Without a public IP, the instance cannot access the internet (Unless we added a NAT gateway)
> Enable public IP address on Jump Host

- terraform/modules/data/aurora.tf
* For some reason, when this is being applied, the error is being thrown:
> Error: Invalid index
> on modules/data/aurora.tf line 20, in module "aurora-metadata-db":
>  20:   password = aws_secretsmanager_secret_version.aurora_postgress_master_password[each.key].secret_string
>    ├────────────────
>    │ aws_secretsmanager_secret_version.aurora_postgress_master_password is object with no attributes
>    │ each.key is "main"
Which is weird, because it is being created (They all use the same local.aurora_rds in their `for_each`)
This is an attempt to add `depends_on` to force those resources to be evaluated first
> Fix rds cluster attributes

- terraform/modules/data/aurora.tf
* The error is still showing, implying the db secret and parameter group index doesn't exit. It may be that the error output from the resource creation is being supressed. This somments out the module for now, to ensure the secret/db-pg creates successfully
> Ensure db paramter groups and secrets create correctly

- .github/workflows/deploy_single_environment.yml
* A refresh is ran during a normal apply
* Running `-refresh-only` on configuration that hasn't yet been applied causes issues
> Remove terraform apply refresh-only

- terraform/main.tf
- terraform/modules/data/outputs.tf
- terraform/modules/network/variables.tf
- terraform/modules/network/vpc.tf
* The security groups for the new RDS needs to be passed to the network module. It uses the terraform-aws-modules/vpc/aws module, which takes in a comma deliminated list of security group ids
> Fix default vpc RDS security groups

- pyproject.toml
This simplifies the process of bumping versions by allowing the use of Commitizen.
> Add Commitizen configuration

- CHANGELOG.md
- pyproject.toml
- **FCL-176**: explicitly set timezones to UTC
- **FCL-176**: automated fixes for "C4" rules (includes unsafe)
- **FCL-176**: automated fixes for "COM" rules
- **FCL-176**: replace instances of shadowing Python builtins
- **FCL-176**: use bound parameters to pass rule ID
- **FCL-176**: replace runtime assert with exception
- **FCL-176**: add timeout when patching a judgment
- **FCL-176**: disable S105 and S106 for known-safe lines
- **FCL-176**: Move update_legislation_table tests
- **FCL-176**: Manual f-string fix for multi-line string
- **FCL-176**: Automated fixes for "UP" rules
- **FCL-176**: Automated fixes for "I" rules
- **FCL-176**: Solve cases of control variables not being used
- **FCL-176**: Refactor some Exception handling
- **FCL-176**: Automated fixes for "B" rules
- …
> Release v6.0.1

- terraform/modules/data/aurora.tf
* We are using v5.3.0 of the terraform-aws-modules/rds-aurora/aws module, which has the `ca_cert_identifier` variable defaulting to `rds-ca-2019`. This certificate expires on August 22nd, and doesn't support automatic certificate rotation.
* This changes the certificate identifier to `rds-ca-rsa4096-g1`, which will update to the latest CA, supporting automatic rotation.
> Update RDS CA Certificate Identifier

- CHANGELOG.md
- pytest.ini
- scripts/test
- src/lambdas/determine_legislation_provisions/index.py
- src/lambdas/update_legislation_table/update_legislation_table/tests/test_fetch_legislation.py
- src/tests/replacer_tests/test_replacer_pipeline.py
- src/tests/requirements.txt
There was an assertion failing in `test_fetch_legislation.py::test_fetch_legislation_integration`. This connects to the Legislation SPARQL endpoint. It looks like the order of the rows returned has changed, and the URL returned is http://www.legislation.gov.uk/ukpga/2023/10 rather than http://www.legislation.gov.uk/ukpga/2023/10/enacted.
It's possible that this change of structure will impact the rest of enrichment, but it's not clear that it will. It's possible it's related to the issues we've been encountering with URLs recently. We've canned the response from legislation.
- \[x\] Increase the version number in src/lambdas/determine_legislation_provisions/index.py
- \[x\] Update CHANGELOG.md
https://national-archives.atlassian.net/browse/FCL-288
> Make Legislation integration test run against a canned version

- CHANGELOG.md
- pytest.ini
- src/lambdas/determine_legislation_provisions/index.py
- src/lambdas/push_enriched_xml/index.py
- src/tests/lambda_tests/push_enriched_xml/test_push_enriched_xml.py
- src/tests/requirements.txt
Enriched press summaries were being submitted to /judgment-url/press`/`summary/1?unlock=True, not press`-`summary.
We special case press-summary as a quick fix.
Added pytest-env as a test dependency to load environment variables -- patch.dict didn't seem to work.
https://national-archives.atlassian.net/browse/FCL-138
> [FCL-138] Fix press summary urls

- src/lambdas/db_backup/dockerfile
- src/lambdas/determine_legislation_provisions/Dockerfile
- src/lambdas/determine_oblique_references/Dockerfile
- src/lambdas/determine_replacements_abbreviations/Dockerfile
- src/lambdas/determine_replacements_caselaw/Dockerfile
- src/lambdas/determine_replacements_legislation/Dockerfile
- src/lambdas/fetch_xml/dockerfile
- src/lambdas/push_enriched_xml/dockerfile
- src/lambdas/update_legislation_table/Dockerfile
- src/lambdas/update_rules_processor/Dockerfile
Reverts nationalarchives/ds-caselaw-data-enrichment-service#635
There appear to be no compilers in this docker image, so numpy cannot be built from source. (Possibly due to the lack of a 3.13 compatible binary?)
```
#11 [7/7] RUN pip install -r requirements.txt --target "/var/task"
#11 0.617 Collecting numpy==1.26.4 (from -r requirements.txt (line 2))
#11 0.649   Downloading numpy-1.26.4.tar.gz (15.8 MB)
#11 0.788      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.8/15.8 MB 133.6 MB/s eta 0:00:00
#11 3.062   Installing build dependencies: started
#11 5.504   Installing build dependencies: finished with status 'done'
#11 5.506   Getting requirements to build wheel: started
#11 5.614   Getting requirements to build wheel: finished with status 'done'
#11 5.617   Installing backend dependencies: …
```
> Revert "chore(deps): update public.ecr.aws/lambda/python docker tag to v3.13"

- .github/workflows/cd_deploy_staging_then_prod.yml
- .github/workflows/ci_lint_and_test.yml
- .github/workflows/deploy_single_environment.yml
- .github/workflows/terraform_plan.yml
- .pre-commit-config.yaml
This one has a warning about too much permissions -- both subtasks almost certainly need it, but this makes zizmor happy.
> Use zizmor as a static ci linter

- CHANGELOG.md
- src/lambdas/determine_legislation_provisions/index.py
- src/tests/replacer_tests/test_make_replacements.py
- src/tests/replacer_tests/test_replacer_pipeline.py
- src/utils/proper_xml.py
- src/utils/tests/test_proper_xml.py
Fix replace_string_with_tag for when the xml fragment string includes uk namespace attributes
Don't love my current fix but I think the whole thing needs a rethink, but this should suffice for now
https://national-archives.atlassian.net/browse/FDD-35
> Fix replace_string_with_tag for when the xml fragment string includes uk namespace attributes

- CHANGELOG.md
- pytest.ini
- src/lambdas/determine_legislation_provisions/index.py
- src/lambdas/push_enriched_xml/index.py
- src/tests/lambda_tests/push_enriched_xml/test_push_enriched_xml.py
Fix push_enriched_xml by stripping the .xml suffix from the specified uri when patching the doc in the database
> Fix push_enriched_xml by stripping the .xml suffix from the specified uri when patching the doc in the database
